import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import localFont from "next/font/local";

import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const pixelMix = localFont({
  src: [
    {
      path: "../../public/fonts/pixelmix.ttf",
      weight: "400",
      style: "normal",
    },

    {
      path: "../../public/fonts/pixelmix_bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-pixelmix",
  display: "swap",
  preload: true,
  fallback: ["sans-serif"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${pixelMix.variable} ${geist.variable}`}>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
